# Generated by Django 5.2.8 on 2025-12-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
    ]
