# Generated by Django 5.2.8 on 2025-12-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_fix_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_status',
            field=models.CharField(choices=[('stable', 'Stable'), ('monitoring', 'Monitoring'), ('improved', 'Improved'), ('critical', 'Critical'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20),
        ),
    ]
