# Generated by Django 5.2.8 on 2025-12-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_notification_options_notification_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('consultation_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow-up', 'Follow-up'), ('check-up', 'Check-up'), ('emergency', 'Emergency'), ('telemedicine', 'Telemedicine')], default='consultation', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('history', models.TextField(blank=True)),
                ('examination', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('treatment_plan', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='webapp.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='webapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='webapp.patient')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['doctor', 'date'], name='webapp_cons_doctor__05e52d_idx'), models.Index(fields=['patient'], name='webapp_cons_patient_e38ebd_idx'), models.Index(fields=['status'], name='webapp_cons_status_f882e7_idx')],
            },
        ),
    ]
