# Generated by Django 5.2.8 on 2025-12-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notify_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
    ]
