# Generated by Django 5.2.8 on 2025-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_patient_notify_email_patient_notify_in_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notify_in_app',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notify_sms',
        ),
        migrations.AddField(
            model_name='doctor',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='notify_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
    ]
