# Generated by Django 5.2.8 on 2025-12-14 17:10

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_patient_address_patient_avatar_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=webapp.models.patient_record_path),
        ),
    ]
