# Generated by Django 5.2.8 on 2025-12-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_patientrecord_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_appointment', models.BooleanField(default=True)),
                ('email_health_alerts', models.BooleanField(default=True)),
                ('sms_appointment', models.BooleanField(default=False)),
                ('sms_health_alerts', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='webapp.patient')),
            ],
        ),
    ]
