# Generated by Django 5.2.8 on 2025-12-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_patientnotificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='district',
            field=models.CharField(default='kigali', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sector',
            field=models.CharField(default='Gasabo', max_length=100),
        ),
    ]
