# Generated by Django 5.2.8 on 2025-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_doctor_district_doctor_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorhospital',
            name='consultation_fee',
        ),
        migrations.AddField(
            model_name='hospital',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
